import type { Metadata } from "next";

import { LegalPage, LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title: "Terms of Service", description: "Basic conventions for using OpenClass accounts, AI, community and paid functions." };

export default function TermsPage() {
  return <LegalPage title="Terms of Service" summary="By using OpenClass, you agree to abide by the following rules. If you are using on behalf of a school or organization, you should ensure that you have the authority to accept the terms on behalf of that organization.">
    <LegalSection title="1. Accounts and Eligibility"><p>Users are expected to provide verifiable account information, protect login credentials, and take responsibility for activity in their accounts. You may not assume another person’s identity, share restricted accounts, bypass access controls, or use automated methods to register in bulk.</p></LegalSection>
    <LegalSection title="2. User Content"><p>Users retain their legal rights to uploaded materials, courses and documents, and authorize OpenClass to process these contents to the extent necessary to provide, protect and improve the services requested by users. Users should ensure that they have the right to upload and use relevant content.</p></LegalSection>
    <LegalSection title="3. AI output"><p>AI output may be inaccurate, incomplete, or unfit for a particular purpose. Users should verify independently before making any teaching, examination, medical, legal, financial or other important decisions. OpenClass does not guarantee that a particular model call will produce a specific result.</p></LegalSection>
    <LegalSection title="4. Acceptable use"><p>You may not use the platform to infringe on the rights of others, spread illegal content, commit fraud or harassment, generate malware, detect non-personal data, interfere with service stability, or circumvent quotas, human verification, security controls and third-party service restrictions.</p></LegalSection>
    <LegalSection title="5. Credits, Payments and Refunds"><p>The price, number of Credits and valid rules displayed on the page are subject to the information at checkout. The rights will be released only after the payment service is confirmed successfully. For repeated deductions, non-delivery or refunds required by law, please contact customer service for verification; the actual consumed model and service costs may affect the refundable amount. Benefits may be temporarily frozen during a chargeback or fraud investigation.</p></LegalSection>
    <LegalSection title="6. Third-party services"><p>Models, payments, emails, communities and external materials may be provided by third parties. The availability, region, price and rules of third-party services may change; users are also bound by the corresponding third-party terms.</p></LegalSection>
    <LegalSection title="7. Service changes and terminations"><p>We may limit functionality for security, compliance, maintenance, or product adjustments and to minimize impact. Accounts may be suspended or terminated if you seriously or repeatedly violate the terms and endanger the safety of the platform or others. Users can export data and cancel their accounts at any time.</p></LegalSection>
    <LegalSection title="8. Boundaries of responsibility"><p>TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED AS IS. OpenClass does not exclude liabilities that cannot be excluded by law; for indirect losses or third-party failures beyond reasonable control, liability shall be handled in accordance with applicable laws.</p></LegalSection>
    <LegalSection title="9. Disputes and Applicable Rules"><p>In the event of a dispute, please contact us for negotiation first. Any mandatory consumer protection, data protection and jurisdictional rules still apply; this clause does not reduce the rights that users have by law and cannot be waived.</p></LegalSection>
  </LegalPage>;
}
