import type { Metadata } from "next";

import { LegalPage, LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy", description: "How OpenClass collects, uses, stores, and protects personal information." };

export default function PrivacyPage() {
  return <LegalPage title="privacy policy" summary="This policy explains how OpenClass handles personal information when providing AI course workbench, data processing, community, account and payment capabilities.">
    <LegalSection title="1. Information we process"><p>We may process account information (email, username, login identity), course and document content, user-uploaded materials, operation and security logs, device and network information, and order status returned by the payment service when purchasing Credits. We do not save complete bank card numbers.</p><p>When a user actively connects to a third-party model or logs in to a service, we only process the information required to complete the connection. The API Key provided by the user will be stored in server-side storage that is isolated by account and has limited access rights, and will not be displayed to other users.</p></LegalSection>
    <LegalSection title="2. Purpose of use"><p>This information is used to create and protect accounts, synchronize the workbench, parse materials, generate or edit learning content, fulfill payments and refunds, prevent abuse, diagnose failures, send user-requested verification codes and security notifications, and comply with legal obligations.</p></LegalSection>
    <LegalSection title="3. AI and third-party services"><p>When a user selects an AI service, payment service, email service or community function, the input necessary to complete the request will be sent to the corresponding service provider and will be subject to its terms and privacy policy. OpenClass will not sell personal information for advertising, nor will private courses be made public by default.</p></LegalSection>
    <LegalSection title="4. Save and delete"><p>Account and course data are usually kept until the user deletes the relevant content or cancels the account; security, accounting and compliance records will be retained for the period required to fulfill legal obligations, handle disputes and prevent fraud. Deletions from the backup are completed as the backup is rotated.</p></LegalSection>
    <LegalSection title="5. User Rights"><p>Users can change their password, log out of all sessions, export data or apply to cancel their account in the account settings, or contact us to request access, correction, deletion or restriction of processing. To protect the account, we may first verify the requester’s identity.</p></LegalSection>
    <LegalSection title="6. Cookies and Security"><p>We use necessary cookies to maintain login and prevent cross-site request forgery, and can use Cloudflare Turnstile to determine whether the request comes from an automated program. We use access control, encrypted transmission, session revocation and auditing measures, but no network service can promise absolute security.</p></LegalSection>
    <LegalSection title="7. Minors"><p>Users who have not reached the age of independent consent in their location should use it with the authorization of their guardian or school. If it is found that personal information of minors has been collected without appropriate authorization, we will process the deletion request after verification.</p></LegalSection>
    <LegalSection title="8. Changes"><p>When there are important changes to the policy, we will update the date and notify you through in-product notifications or appropriate contact information. Users can review the new version and decide whether to accept it before continuing.</p></LegalSection>
  </LegalPage>;
}
