location = /community {
  proxy_pass http://127.0.0.1:9080/;
}

location /community/ {
  proxy_pass http://127.0.0.1:9080/;
}

location /answer/ {
  proxy_pass http://127.0.0.1:9080;
}

location /uploads/ {
  proxy_pass http://127.0.0.1:9080;
}
